CREATE TABLE IF NOT EXISTS `my_table` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `TITLE` VARCHAR(65536) NOT NULL,
  `SORT` INT(11) NULL DEFAULT 500,
  `CREATED` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`));

CREATE TABLE IF NOT EXISTS `my_ref_table` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(45) NOT NULL,
  `REF` INT(11) NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `REF`
    FOREIGN KEY (`REF`)
    REFERENCES `my_table` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);